# Generated by Django 5.2.1 on 2025-08-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_ai_insights_notification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="ai_insights_notification",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="marketing_alerts",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="weekly_report_notification",
        ),
    ]
