# Generated by Django 5.2.1 on 2025-08-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usernotificationsetting_delete_notificationsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="marketing_alerts",
            field=models.BooleanField(default=False),
        ),
    ]
