# Generated by Django 5.2.1 on 2025-08-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_usernotificationsetting_marketing_alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotificationsetting",
            name="marketing_alerts",
            field=models.BooleanField(default=True),
        ),
    ]
