# Generated by Django 5.2.1 on 2025-08-14 01:02

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_notice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="notice",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notice",
            name="public_id",
            field=models.CharField(
                db_index=True,
                default=users.models._gen_public_id,
                max_length=40,
                unique=True,
            ),
        ),
    ]
