# Generated by Django 5.2.1 on 2025-08-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_notice_is_active_alter_notice_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
