# Generated by Django 5.2.1 on 2025-08-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_notice_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
