# Generated by Django 5.2.1 on 2025-08-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "spend",
                    models.PositiveIntegerField(default=0, verbose_name="지출액"),
                ),
                ("sales", models.PositiveIntegerField(default=0, verbose_name="매출")),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="클릭 수"),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="노출 수"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_performances",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "campaign")},
            },
        ),
    ]
