# Generated by Django 5.2.5 on 2025-08-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=50)),
                ('keyword', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=1)),
                ('source', models.CharField(default='public', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('region', 'keyword')},
            },
        ),
    ]
