# Generated by Django 5.2.5 on 2025-08-14 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trendkeyword",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="trendkeyword",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="trendkeyword",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="trendkeyword",
            index=models.Index(
                fields=["region", "-created_at"], name="home_trendk_region_5a158e_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="trendkeyword",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="trendkeyword",
            name="source",
        ),
        migrations.RemoveField(
            model_name="trendkeyword",
            name="updated_at",
        ),
    ]
