# Generated by Django 5.2.1 on 2025-08-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_trendkeyword_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trendkeyword",
            unique_together={("region", "keyword")},
        ),
    ]
