# Generated by Django 5.2.1 on 2025-08-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_trendkeyword_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trendkeyword",
            unique_together=set(),
        ),
    ]
