# Generated by Django 5.2.1 on 2025-08-12 13:20

from django.db import migrations


def seed(apps, schema_editor):
    Provider = apps.get_model("integrations", "Provider")
    Provider.objects.get_or_create(
        code="facebook",
        defaults={
            "label": "Facebook",
            "scopes": ["pages_read_engagement", "ads_management"],
            "category": "account",
        },
    )
    Provider.objects.get_or_create(
        code="instagram",
        defaults={
            "label": "Instagram",
            "scopes": ["instagram_basic", "ads_management"],
            "category": "account",
        },
    )


def unseed(apps, schema_editor):
    Provider = apps.get_model("integrations", "Provider")
    Provider.objects.filter(code__in=["facebook", "instagram"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
