# Generated by Django 5.2.1 on 2025-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_seed_providers"),
    ]

    operations = []
