# Generated by Django 5.2.1 on 2025-08-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_seed_providers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=100)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("account_handle", models.CharField(blank=True, max_length=200)),
                ("account_business", models.BooleanField(default=False)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("revoked", "revoked"),
                            ("disconnected", "disconnected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("disconnect_reason", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="integrations.provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "provider", "account_id"],
                        name="integration_user_id_de23f1_idx",
                    )
                ],
            },
        ),
    ]
