# Generated by Django 5.2.1 on 2025-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, unique=True
            ),
        ),
    ]
