# Generated by Django 5.2.1 on 2025-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_integration_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pos_providers",
            },
        ),
    ]
