# Generated by Django 5.2.1 on 2025-08-13 20:32

import django.db.models.deletion
from django.db import migrations, models

import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_posprovider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posprovider",
            name="active",
        ),
        migrations.RemoveField(
            model_name="posprovider",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="posprovider",
            name="updated_at",
        ),
        migrations.AlterModelTable(
            name="posprovider",
            table=None,
        ),
        migrations.CreateModel(
            name="PosConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        default=integrations.models.gen_public_id,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("store_external_id", models.CharField(max_length=100)),
                (
                    "store_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("credentials", models.JSONField(default=dict)),
                ("webhook_callback_url", models.URLField(blank=True, default="")),
                (
                    "webhook_signing_secret",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="integrations.posprovider",
                    ),
                ),
            ],
        ),
    ]
