# Generated by Django 5.2.1 on 2025-08-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_remove_posprovider_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posconnection",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posconnection",
            name="last_ping_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
