# Generated by Django 5.2.1 on 2025-08-17 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_posconnection_last_error_posconnection_last_ping_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="posprovider",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="posprovider",
            name="auth",
            field=models.CharField(default="api_key", max_length=50),
        ),
        migrations.AddField(
            model_name="posprovider",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="posprovider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="posprovider",
            table="pos_providers",
        ),
    ]
