# Generated by Django 5.2.1 on 2025-08-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0010_posconnection_disconnected_at_posconnection_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="posconnection",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="posconnection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("provider", "store_external_id"),
                name="uniq_active_pos_store_per_provider",
            ),
        ),
    ]
