# Generated by Django 5.2.1 on 2025-08-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0012_cleanup_and_recreate_indexes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="posconnection",
            name="uniq_active_pos_store_per_provider",
        ),
        migrations.RemoveConstraint(
            model_name="posconnection",
            name="uniq_active_pos_store_per_provider",
        ),
        migrations.RemoveIndex(
            model_name="posconnection",
            name="pos_prov_store_idx_v2",
        ),
    ]
