# Generated by Django 5.2.1 on 2025-08-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0013_remove_posconnection_uniq_active_pos_store_per_provider_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="posconnection",
            new_name="pos_prov_store_idx_v2",
            old_name="pos_prov_store_idx",
        ),
    ]
