# Generated by Django 5.2.1 on 2025-08-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="캠페인 이름")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "진행중"), ("ended", "종료")],
                        default="active",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "channel",
                    models.CharField(blank=True, max_length=50, verbose_name="채널"),
                ),
                (
                    "spend",
                    models.PositiveIntegerField(default=0, verbose_name="총 소진액"),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(default=0, verbose_name="총 매출"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="클릭 수"),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="노출 수"),
                ),
                (
                    "roas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ROAS",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "objectives",
                    models.TextField(blank=True, verbose_name="캠페인 목표"),
                ),
                (
                    "performance",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="종합 성과"
                    ),
                ),
                (
                    "creative",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="소재 정보"
                    ),
                ),
                (
                    "target",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="타겟 정보"
                    ),
                ),
                (
                    "budget",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="예산 정보"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
        ),
    ]
