# Generated by Django 5.2.5 on 2025-08-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_insights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insight",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="insight",
            name="reason_text",
            field=models.CharField(max_length=255),
        ),
    ]
