# Generated by Django 5.2.1 on 2025-08-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_insights", "0002_insight_description_alter_insight_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("growth", "Growth"),
                            ("retention", "Retention"),
                            ("expansion", "Expansion"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="insight",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="기존 전략 카드에 노출할 아이콘(예: 📣, 🧩 등)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="insight",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="insight",
            name="reason_icon",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="reason_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="insight",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="기존 전략에서 노출할 태그 리스트",
                related_name="insights",
                to="ai_insights.insighttag",
            ),
        ),
    ]
