# Generated by Django 5.2.1 on 2025-08-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_insights", "0003_insighttag_insight_icon_insight_is_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insight",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="icon",
            field=models.CharField(default="ICON", max_length=32),
        ),
        migrations.AlterField(
            model_name="insight",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="insights", to="ai_insights.insighttag"
            ),
        ),
        migrations.AlterField(
            model_name="insighttag",
            name="type",
            field=models.CharField(
                choices=[
                    ("growth", "growth"),
                    ("retention", "retention"),
                    ("expansion", "expansion"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InsightAnalysisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(default="", max_length=10)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_items",
                        to="ai_insights.insight",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="InsightRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("item_icon", models.CharField(default="", max_length=10)),
                ("item_title", models.CharField(max_length=200)),
                ("item_description", models.TextField()),
                (
                    "insight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="ai_insights.insight",
                    ),
                ),
            ],
        ),
    ]
